Transform: AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/example
      Handler: app.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps

  MyFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/example
      Handler: app.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps

  MyFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/example
      Handler: app.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
