Transform: AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/example
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps